name: Test GitHub Actions
run-name: ${{ github.actor }} is testing 🚀
on: 
  push:
  pull_request:
  schedule:
    - cron: '59 1,13 * * *' 
jobs:
  General-Features:   
    runs-on: ubuntu-latest
    steps:
      - name: Echoing a content
        run: echo "This is an example content..."
      - name: The Author
        run: echo "The author is> ${{ github.actor }}"

  ENV-Feature:
    env:
      superSecretKey: ${{ secrets.SUPER_SECRET_KEY }}
      firstName: "Seyha"
      lastName: "Soeurn"
    runs-on: macos-13
    steps:
      - name: Showing Secret Key
        run: echo "The secret key is> ${{ env.superSecretKey }}"
      - name: About me
        run: echo "My name is ${{ env.firstName }} ${{ env.lastName }}"

  Event-And-If-Features:
    runs-on: windows-2019
    steps:
      - if: github.event == 'pull_request' || github.event == 'push'
        name: Checking GitHub event(s)
        run: echo "The ran event is not Schedule. <${{ github.event }}>"
      - if: github.event != 'pull_request' || github.event != 'push'
        name: Checking GitHub event(s)
        run: echo "The ran event is Schedule. <${{ github.event }}>"

  Needs-Feature:
    needs: [Event-And-If-Features, ENV-Feature]
    runs-on: ubuntu-latest
    steps:
      - name: Message
        run: echo "Jobs Event-And-If-Features & ENV-Feature are passed."

  Job-For-Output:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  Output-Feature:
    runs-on: ubuntu-latest
    needs: Job-For-Output
    steps:
      - env:
          OUTPUT1: ${{ needs.Job-For-Output.outputs.output1 }}
          OUTPUT2: ${{ needs.Job-For-Output.outputs.output2 }}
        run: echo "$OUTPUT1 $OUTPUT2"